# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

#services:
#  - postgresql

env:
  global:
    - CODECOV_TOKEN="bffadaa2-6664-4720-94fc-ebc7e72afafc"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту laiwiense@gmail.com
notifications:
  email:
    recipients:
      -laiwiense@gmail.com
    on_success: never # default: change
    on_failure: always # default: always